
<?php get_header(); ?>




  <div class="line__hero noline">
    <div class="l__1260">
      <div class="line__hero__flex">
        <div class="line__hero__f1" data-ix="load-2">Privacy Policy</div>
        <div class="line__hero__f3" data-ix="load-3">Effective date: April 16, 2018</div>
      </div>
    </div>
  </div>
  <div class="privacy__wrap" data-ix="scroll">
    <div class="l__1260">
      <p class="privacy__f1">This Privacy Policy describes the ways in which Aligned Genetics, Inc. (“Logos Biosystems”, “we”, or “us”) collects, holds and uses information about individual persons who visit www.logosbio.com (the “Site”). BY USING THE SITE, YOU CONSENT TO THE COLLECTION AND USE OF INFORMATION (INCLUDING PERSONAL DATA) AS SET FORTH IN THIS PRIVACY POLICY. YOU ALSO ACKNOWLEDGE THAT WE MAY PERIODICALLY CHANGE, MODIFY, ADD, REMOVE, OR OTHERWISE UPDATE THIS PRIVACY POLICY IN OUR DISCRETION. When we do make any changes, modifications, additions or removals to this Privacy Policy, we will give you notice of the revised Privacy Policy by posting the revised Privacy Policy on the Site and by revising the “effective date” at the top of this Privacy Policy. However, we will always handle your Information with at least as much protection as provided in the version of the Privacy Policy that was in effect at the time of collection. You are responsible for regularly reviewing the current privacy policy. Our Privacy Policy is located on the Site’s homepage and is also available on any page where Personal Data is requested. This Privacy Policy applies only to information we collect from this Site and does not apply to any other website or business activity of Logos Biosystems. At data collection points within the Site, further explanation may be provided, where appropriate, as to the purposes for which the data will be used.</p>
      <p class="privacy__f2">INFORMATION WE COLLECT</p>
      <p class="privacy__f1">The term “Personal Data” as used in this Privacy Policy refers to information such as your name, email address, mailing address, telephone number, and any other information that can be used to identify you or allows us to contact you physically or online. We may collect Personal Data when you register with the Site, place an order on the Site, send us an email or otherwise contact us through the Site, or if you voluntarily choose to provide it to us.</p>
      <p class="privacy__f1">You can choose not to provide Personal Data to us. However, if you do not provide such information, you will not be able to register to use the Site, so your ability to use the Site will be limited to those web pages available to unregistered users of the Site. Additionally, you will not be able to place orders on the Site or contact us with questions via email or otherwise through the Site.</p>
      <p class="privacy__f1">The term “Automatic Information” is information automatically collected by our web server (which may be hosted by a third-party) that your web browser makes available whenever you visit our Site, such as your computer’s IP address, browser type, operating system version, and information about the website that you visited before visiting the Site. The term “Automatic Information” includes “cookies” and “tags,” each of which the Site uses. A cookie is a small text file that a website’s server places on a computer’s web browser. The cookie stores information which may be read by the website’s server about the browsing activities of the computer user on the Site. This includes information such as pages and content viewed, the time and duration of visits, search queries entered into search engines, and whether a computer user clicked on an advertisement. Cookies also can be used to maintain data related to a particular individual, including passwords or items in an online shopping cart. In some contexts, such as where a number of separate websites participate in a network, cookies can be used to track a computer user across different sites. Cookies do not alter your hard drive in any way and cannot be used to access any personal information from your computer. Cookies are used as a standard practice by many sites. As important as cookies are to our Site, we understand that this might make you uncomfortable. If you would prefer not to accept cookies from our Site or any other site, you can modify the setting on the web browser installed on your computer. Please refer to your browser&#x27;s online help feature or the user&#x27;s manual for instructions on how to do this. However, if you refuse to accept cookies from the Site, it is possible that all or some portions of the Site may not function as intended.</p>
      <p class="privacy__f1">We may deploy these tags/cookies through a third-party advertising partner or a web analytical service partner which may be located and store the respective information (including your IP-address) in a foreign country. These tags/cookies are placed on both online advertisements that bring users to this site and on different pages of this site. We use this technology to measure the visitors&#x27; responses to our sites and the effectiveness of our advertising campaigns (including how many times a page is opened and which information is consulted) as well as to evaluate your use of this Site. The third-party partner or the web analytical service partner may be able to collect data about visitors to our and other sites because of these internet tags/cookies, may compose reports regarding the Site’s activity for us and may provide further services which are related to the use of the Site and the internet. They may provide such information to other parties if there is a legal requirement that they do so, or if they hire the other parties to process information on their behalf. If you would like more information about web tags and cookies associated with on-line advertising or to opt-out of third-party collection of this information, please visit the Network Advertising Initiative website <a href="http://www.networkadvertising.org/" class="privacy__f1--link">http://www.networkadvertising.org</a>.</p>
      <p class="privacy__f1">Automatic Information may be tied to your Personal Data after Personal Data has been submitted and, therefore, will be treated as Personal Data to the extent it may be tied to Personal Data.</p>
      <p class="privacy__f1">The term “Information” as used herein means, collectively, Personal Data and Automatic Information.</p>
      <p class="privacy__f2">INTENDED USE OF INFORMATION</p>
      <p class="privacy__f1">Most of our services do not require any form of registration, allowing you to visit our site without telling us who you are. However, some services offered on the Site may require you to provide us with Personal Data. In these situations, if you choose to withhold any Personal Data requested by us, it may not be possible for you to gain access to certain parts of the Site and for us to respond to your query.</p>
      <p class="privacy__f1">We collect and use information to fulfill product orders and respond appropriately to requests for information and services. We also use the information to provide, maintain, and improve the Site, to notify you about changes to the Site, to allow you to participate in interactive features of the Site when you choose to do so, to provide customer care and support, to monitor the usage of the Site, to conduct marketing analysis and research, and to detect, prevent, and address technical issues. If you order products through the Site, we may contact you by email to provide information about your order. If you have an account with our site, we may contact you by email about your account status or changes to relevant agreements or policies.</p>
      <p class="privacy__f1">You provide Automatic Information to us merely by visiting the Site. We may collect and use Automatic Information to customize your Site experience, to generally help us learn about the usage of the Site, to help us run and maintain the Site, , to monitor the usage of the Site, to conduct marketing analysis and research, and other similar uses.</p>
      <p class="privacy__f2">NON-DISCLOSURE OF INFORMATION</p>
      <p class="privacy__f1">We will not disclose your personal information to third parties. Unless we have your permission or are required by law, we will only transfer your personal data to third parties who act for or on our behalf, for further processing in accordance with the purpose(s) for which the data were originally collected or may otherwise be lawfully processed, such as: Logos Biosystems entities, distributors who deliver your order and/or provide billing services, credit card companies for payment processing, and other third parties who provide services to us. These third parties may provide a variety of services to us including, without limitation, hosting this Site, providing technical support, processing and storing user information, updating your customer information records in our database (including both physical address and email address verification), and sending or coordinating the sending of marketing communications on our behalf. These third parties will only receive access to your personal information as necessary to carry out the services they are performing for us and use your personal data for the agreed upon purpose only.</p>
      <p class="privacy__f1">Third party site, platform, or service operators, such as Twitter, Facebook, Google, LinkedIn, or Stripe, may collect, or require that we provide, your information relating to the Services. Any information made available to such third parties will be used by them in accordance with their own privacy policies. We will not be responsible for the contents of those third party privacy policies. We advise you to carefully review their terms before accepting them.</p>
      <p class="privacy__f2">RIGHT OF ACCESS, CORRECTION AND OBJECTION</p>
      <p class="privacy__f1">Whenever we process Personal Data, we take reasonable steps to ensure that your Personal Data is kept accurate and up-to date for the purposes for which it was collected. We will provide you with the ability to object to the processing of your Personal Data if such processing is not reasonably required for a legitimate business purpose as described in this policy or our compliance with law. In the case of electronic direct marketing, we will provide you with a method to opt out of receiving further marketing materials or with a method to opt in if required by law. If you wish to contact us regarding our use of your Personal Data or object to the processing of your Personal Data, please email us at <a href="mailto:info@logosbio.com">info@logosbio.com</a>. If you contact us, please note the specific information you would like us to correct, update, or delete plus a proper identification of you. Requests to delete personal data will be subject to any applicable legal and ethical reporting or document filing or retention obligations imposed on us.</p>
      <p class="privacy__f2">SECURITY AND CONFIDENTIALITY</p>
      <p class="privacy__f1">The security of your data is important to us. To ensure the security of the information that we collect online, we use data networks protected by industry standard firewall and password protection. We take measures to protect your Personal Data from loss, misuse, unauthorized access, disclosure, alteration or destruction. However, information transmitted over the Internet or stored electronically is not 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot ensure, warrant or guarantee the security or integrity of such information. We will not be responsible for disclosure of any information due to errors in transmission or the unauthorized actions of third parties. Please keep your username and password confidential, protect against unauthorized access to your password and to your computer, and sign off when finished using a shared computer.</p>
      <p class="privacy__f2">DATA TRANSFER ABROAD</p>
      <p class="privacy__f1">Logos Biosystems is headquartered in South Korea with branches in the United States and France. We have databases in different countries, some of which are operated locally, and some of which are operated by third parties on our behalf. We may transfer your data to one of the databases outside your country of domicile, potentially including countries which may not require an adequate level of protection for your Personal Data compared with that provided in your country. However, we will take measures to ensure the standards of security with respect to such databases holding your Personal Data will equal or exceed the standards of protection as existed prior to such transfer.</p>
      <p class="privacy__f2">PERSONAL INFORMATION AND CHILDREN</p>
      <p class="privacy__f1">The services available on this site are intended for persons 18 years of age and older. We will not knowingly collect, use or disclose Personal Data from a minor under the age of 18. We abide by laws designed to protect children.</p>
      <p class="privacy__f2">LINKS TO OTHER SITES</p>
      <p class="privacy__f1">Our Site may contain links to other third party sites that are not operated by us. If you click on a third party link, you will be directed to that third party&#x27;s site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third party sites or services.</p>
      <p class="privacy__f2">CHOICES AVAILABLE TO YOU</p>
      <p class="privacy__f1">As discussed above, you can always choose not to provide Information, even though it might be needed to make a purchase or to take advantage of certain Site features. You can add or update certain information on certain pages. When you update information, we may keep a copy of the prior version for our records. If you do not want to receive email or other mail from us, please adjust your preferences accordingly. Note, however, that even if you do not want to receive Terms of Use and other legal notices from us, such as notices of updates to this Privacy Policy, those notices will still govern your use of the Site, and it is your responsibility to review them for changes.</p>
      <p class="privacy__f1">The Help portion of the toolbar on most browsers will tell you how to prevent your browser from accepting new cookies, how to have the browser notify you when you receive a new cookie, or how to disable cookies altogether. Additionally, you can disable or delete similar data used by browser add-ons, such as Flash cookies, by changing the add-on’s settings or visiting the Web site of its manufacturer. However, because cookies allow you to take advantage of some of the Site’s essential features, we recommend that you leave them turned on. For instance, if you block or otherwise reject our cookies, you will not be able to add items to your Shopping Cart, proceed to Check Out, or use any of the Site’s products and services that require you to Sign In.</p>
      <p class="privacy__f2">CONTACT US</p>
      <p class="privacy__f1">If you have any questions or comments about this Privacy Policy or about how any information you submit to us is used, please contact us at <a href="mailto:info@logosbio.com" class="privacy__f1--link">info@logosbio.com.</a>
      </p>
    </div>
  </div>



  <?php get_footer(); ?>